In [9]:
from omegaconf import OmegaConf
from datasets import load_data
import numpy as np
config = OmegaConf.load("./configs/default_config.yaml")

for dataset in [ 'stanford_cars', ]:
                #'caltech101', 'dtd', 'eurosat' ,
                # 'fgvc-aircraft-2013b', 'flowers-102', 'oxford-iiit-pet'
                #'Imagenette', 'CIFAR10', 'CIFAR100',]:
    
    config.dataset = dataset
    train_dataset, val_dataset, test_dataset, N, train_transform, transform = load_data(False, config) 

    print(dataset, len(train_dataset), len(val_dataset), len(test_dataset),  N) #min(pixels[0][0]),  max(pixels[0][0]),

datadir /home/mheuillet/Desktop/robust_training/data
stanford_cars 6922 1222 1500 196


/tmp/ipykernel_91218/1689061401.py:14: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  pixels = np.array(image)


In [10]:
image, label = test_dataset[0]  # Extract the image and label
pixels = np.array(image)
print(pixels) # the images in the test set have been transformed to floats so we cant apply the corruptions directly

[[[0.5176471  0.5176471  0.5176471  ... 0.2901961  0.3019608  0.32941177]
  [0.5176471  0.5176471  0.5176471  ... 0.41568628 0.36078432 0.34509805]
  [0.5176471  0.5176471  0.5176471  ... 0.4745098  0.5019608  0.5254902 ]
  ...
  [0.18039216 0.19215687 0.19215687 ... 0.03529412 0.03529412 0.03529412]
  [0.19215687 0.19607843 0.1882353  ... 0.03529412 0.03529412 0.03529412]
  [0.21176471 0.20784314 0.1764706  ... 0.03529412 0.03529412 0.03529412]]

 [[0.5921569  0.5921569  0.5921569  ... 0.30588236 0.3254902  0.3647059 ]
  [0.5921569  0.5921569  0.5921569  ... 0.42745098 0.3764706  0.36078432]
  [0.5921569  0.5921569  0.5921569  ... 0.49019608 0.5254902  0.5568628 ]
  ...
  [0.17254902 0.18431373 0.18431373 ... 0.03921569 0.03921569 0.03921569]
  [0.18431373 0.1882353  0.18039216 ... 0.03921569 0.03921569 0.03921569]
  [0.20392157 0.2        0.16862746 ... 0.03921569 0.03921569 0.03921569]]

 [[0.65882355 0.65882355 0.65882355 ... 0.34509805 0.34901962 0.38039216]
  [0.65882355 0.658823

/tmp/ipykernel_91218/2508489123.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  pixels = np.array(image)


In [ ]:
from torchvision import datasets
from imagecorruptions import corrupt


datadir = './data'

# test_dataset = test_full = datasets.Caltech101(root=datadir, download=False)
# test_dataset = test_dataset = datasets.Flowers102(root=datadir, split='test', download=False)
# test_dataset = datasets.DTD(root=datadir, split='test', download=False)
test_dataset = datasets.StanfordCars(root=datadir, split='test', download=False, )
# test_dataset = datasets.FGVCAircraft(root=datadir, split='test', download=False,)
# test_dataset = datasets.OxfordIIITPet(root=datadir, split='test', download=False )

x,y = test_dataset[0]
print( np.array(x) ) # here we can apply the corruptions because this is raw integer pixelate data 



#this is the set of corruptions accessible on which the portfolio should be based:
CORRUPTIONS = [
    'gaussian_noise', 'shot_noise', 'impulse_noise', 'defocus_blur', 
    'frost', 'fog', 'brightness', 'contrast', 'elastic_transform', 
    'pixelate', 'jpeg_compression'
]

SEVERITY_LEVELS = [2, 3, 4]

corrupted_image = corrupt(np.array(x), corruption_name='jpeg_compression', severity=1)




[[[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


In [ ]:
### don't pay attention to this cell

# EuroSAT: seulement 8 runs on complete et tous les autres OOM
# Caltech: 26 runs ok, 
# Stanford Cars: 34 ok
# Aircraft: 26 ok
# DTD : 26 ok
# Oxford pet: 26 ok
# Flowers: 26 ok

stanford_cars = 6922 + 1222 + 8041 
caltech101 = 5899 + 1042 + 1736 
dtd = 1880 + 1880 + 1880 
eurosat = 18360 + 3240 + 5400 
fgvcaircraft2013b =  3334 + 3333 + 3333 
flowers102 = 1020 + 1020 + 6149 
oxfordiiitpet = 3128 + 552 + 3669 

print(eurosat, caltech101, dtd, fgvcaircraft2013b, flowers102, oxfordiiitpet, stanford_cars)

from PIL import Image
import torchvision.datasets as datasets

# Initialize the Caltech101 dataset without transformations
caltech101_sample = datasets.Caltech101(root='./data', download=False)
print(len(caltech101_sample))
for i in range( len(caltech101_sample) ) :
    image, label = caltech101_sample[i]

    # Check the image mode
    # print(f"Image Mode: {image.mode}")  # Expected: 'RGB'
    if image.mode != 'RGB':
        print('issue')